using TilemapShadowCaster.Runtime;
using UnityEditor;

namespace TilemapShadowCaster.Editor
{
    [CustomEditor(typeof(PathShadow))]
    public class PathShadowEditor : UnityEditor.Editor
    {
        public override void OnInspectorGUI()
        {
            EditorGUILayout.HelpBox(
                "This is an autogenerated object from the TilemapShadowCaster2D, it renders a specific shadow path from the parent tilemap, don't work on this gameObject, it will be destroyed eventually",
                MessageType.None);
        }
    }
}